-- Creates the tables for the MOL taxonomy in CartoDB, based on create_tables.sql
-- Renamed the tables to add an '' prefix to distinguish them from
-- old tables and keeping it all together.
-- 
-- LJV
-- 
-- Creates all tables for the MOL taxonomy database schema.
-- This code was initially generated by Parse::SQL::Dia version 0.23,
-- with additional SQL customizations by hand afterwards.

DROP TABLE IF EXISTS "taxon_concepts";
DROP TABLE IF EXISTS "taxonomies";
DROP TABLE IF EXISTS "names"; ---
DROP TABLE IF EXISTS "name_spellings";
DROP TABLE IF EXISTS "names_to_taxonconcepts";
DROP TABLE IF EXISTS "tc_relationships";
DROP TABLE IF EXISTS "rank_systems";
DROP TABLE IF EXISTS "ranks";
DROP TABLE IF EXISTS "citations";



-- get_schema_create
create table "taxon_concepts" (
   tc_id       serial not null  ,
   parent_id   integer          ,
   taxonomy_id integer          ,
   rank_id     integer          ,
   depth       integer          ,
   sort_order  integer DEFAULT 0,
   constraint pk_taxon_concepts primary key (tc_id)
);

create table "taxonomies" (
   taxonomy_id integer not null,
   name        text            ,
   ismaster    boolean         ,
   root_tc_id  integer         ,
   citation_id integer         ,
   constraint pk_taxonomies primary key (taxonomy_id)
);

create table "names" (
   name_id     serial not null,
   namestr     text            ,
   citation_id integer
);

create table "name_spellings" (
   name_id  integer ,
   spelling text    
);

-- Make sure that the prefix/postfix always have a default value of '' so that
-- queries don't have to worry about handling NULL values.  Also set the default
-- value of preferred to FALSE.
create table "names_to_taxonconcepts" (
   tc_id    integer                  ,
   name_id integer                   ,
   preferred boolean DEFAULT FALSE   ,
   authordisp_prefix text DEFAULT '' ,
   authordisp_postfix text DEFAULT ''
);

create table "tc_relationships" (
   master_tc_id      integer ,
   alt_tc_id         integer ,
   relationshiptype text    
);

create table "rank_systems" (
   ranksys_id  integer ,
   namestr     text    ,
   description text    ,
   constraint pk_rank_systems primary key (ranksys_id)
);

create table "ranks" (
   rank_id            integer not null,
   ranksys_id         integer         ,
   namestr            text            ,
   nearest_parent_id  integer         ,
   obligate_parent_id integer         ,
   constraint pk_ranks primary key (rank_id)
);

create table "citations" (
   citation_id   serial not null,
   citationstr   text            ,
   URL           text            ,
   DOI           text            ,
   authordisplay text            ,
   constraint pk_citations primary key (citation_id)
);






-- Cartodbfy
SELECT cartodb.cdb_cartodbfytable('taxon_concepts');
SELECT cartodb.cdb_cartodbfytable('taxonomies');
SELECT cartodb.cdb_cartodbfytable('names');
SELECT cartodb.cdb_cartodbfytable('name_spellings');
SELECT cartodb.cdb_cartodbfytable('names_to_taxonconcepts');
SELECT cartodb.cdb_cartodbfytable('tc_relationships');
SELECT cartodb.cdb_cartodbfytable('rank_systems');
SELECT cartodb.cdb_cartodbfytable('ranks');
SELECT cartodb.cdb_cartodbfytable('citations');






-- Add indices
CREATE INDEX taxon_concepts_tc_id_btree
  ON public.taxon_concepts
  USING btree (tc_id);
CREATE INDEX taxon_concepts_parent_id_btree
  ON public.taxon_concepts
  USING btree (parent_id);
CREATE INDEX taxon_concepts_taxonomy_id_btree
  ON public.taxon_concepts
  USING btree (taxonomy_id);
CREATE INDEX taxon_concepts_rank_id_btree
  ON public.taxon_concepts
  USING btree (rank_id);



CREATE INDEX taxonomies_taxonomy_id_btree
  ON public.taxonomies
  USING btree (taxonomy_id);
CREATE INDEX taxonomies_ismaster_btree
  ON public.taxonomies
  USING btree (ismaster);


CREATE INDEX names_name_id_btree
  ON public.names
  USING btree (name_id);
CREATE INDEX names_namestr_btree
  ON public.names
  USING btree (namestr);


CREATE INDEX name_spellings_name_id_btree
  ON public.name_spellings
  USING btree (name_id);
CREATE INDEX name_spellings_spelling_btree
  ON public.name_spellings
  USING btree (spelling);


CREATE INDEX names_to_taxonconcepts_tc_id_btree
  ON public.names_to_taxonconcepts
  USING btree (tc_id);
CREATE INDEX names_to_taxonconcepts_name_id_btree
  ON public.names_to_taxonconcepts
  USING btree (name_id);
CREATE INDEX names_to_taxonconcepts_preferred_btree
  ON public.names_to_taxonconcepts
  USING btree (preferred);



CREATE INDEX tc_relationships_master_tc_id_btree
  ON public.tc_relationships
  USING btree (master_tc_id);
CREATE INDEX tc_relationships_alt_tc_id_btree
  ON public.tc_relationships
  USING btree (alt_tc_id);
CREATE INDEX tc_relationships_relationshiptype_btree
  ON public.tc_relationships
  USING btree (relationshiptype);



CREATE INDEX rank_systems_ranksys_id_btree
  ON public.rank_systems
  USING btree (ranksys_id);



CREATE INDEX ranks_rank_id_btree
  ON public.ranks
  USING btree (rank_id);
CREATE INDEX ranks_ranksys_id_btree
  ON public.ranks
  USING btree (ranksys_id);
CREATE INDEX ranks_namestr_btree
  ON public.ranks
  USING btree (namestr);




CREATE INDEX citations_citation_id_btree
  ON public.citations
  USING btree (citation_id);



CREATE SEQUENCE public.names_name_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 57371
  CACHE 1;
ALTER TABLE public.names_name_id_seq
  OWNER TO "cartodb_user_b4ba2644-9de0-43d0-86fb-baf3b484ccd3";










-- Skip for now, just copy the data from Litoria
/*
-- Set up the minimal pieces needed for the MOL backbone taxonomy.
-- The MOL backbone taxonomy begins with a single top-level taxon
-- concept, the unranked clade "Eukaryota".  The following INSERT
-- commands create the taxonomy definition and citation along with
-- the root taxon concept, name, and citation.
INSERT INTO taxonomies
    (taxonomy_id, name, ismaster, root_tc_id, citation_id)
    VALUES (1, 'MOL backbone', true, 1, 1);

INSERT INTO citations
    (citation_id, citationstr, url, doi, authordisplay)
    VALUES (1, 'Jetz, W., J.M. McPherson, R.P. Guralnick. 2012. Integrating biodiversity distribution knowledge: toward a global map of life. Trends in Ecology and Evolution 27: 151-159.', 'http://www.sciencedirect.com/science/article/pii/S0169534711002679', 'doi:10.1016/j.tree.2011.09.007', 'Jetz et al. 2012');
INSERT INTO citations
    (citation_id, citationstr, url, doi, authordisplay)
    VALUES (2, 'Chatton, É. 1925. Pansporella perplexa: amoebiens à spores protégées parasite de daphnies: réflexions sur la biologie et la phylogénie des protozoaires. Annales des Sciences Naturelles, séries Botanique et Zoologie (10) 8: 1–84.', null, null, 'Chatton 1925');
INSERT INTO taxon_concepts
    (tc_id, parent_id, taxonomy_id, rank_id, depth)
    VALUES (1, 0, 1, 0, 0);
INSERT INTO names
    (name_id, namestr, preferred, citation_id)
    VALUES (1, 'Eukaryota', true, 2);
INSERT INTO names_to_taxonconcepts
    (tc_id, name_id, authordisp_prefix, authordisp_postfix)
    VALUES (1, 1, '', '');

-- Update the sequences to reflect the INSERT commands above.
SELECT setval('citations_citation_id_seq', 3, false);
SELECT setval('taxon_concepts_tc_id_seq', 2, false);
SELECT setval('names_name_id_seq', 2, false);
*/
